on:
  issue_comment:
    types: [ created ]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Pull Request Validation
      uses: shovel-org/GithubActions@main
      if: startsWith(github.event.comment.body, '/verify') && contains(fromJSON('["Ash258"]'), github.event.comment.user.login)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
